# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\")\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0bLogResponse\x12\x14\n\x0c\x64\x65\x64uplicated\x18\x01 \x01(\x08\"\x10\n\x0eGetLogsRequest\"#\n\x0fGetLogsResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\x83\x01\n\x0eLoggingService\x12\x33\n\x06\x41\x64\x64Log\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12<\n\x07GetLogs\x12\x17.logging.GetLogsRequest\x1a\x18.logging.GetLogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=67
  _globals['_LOGRESPONSE']._serialized_start=69
  _globals['_LOGRESPONSE']._serialized_end=104
  _globals['_GETLOGSREQUEST']._serialized_start=106
  _globals['_GETLOGSREQUEST']._serialized_end=122
  _globals['_GETLOGSRESPONSE']._serialized_start=124
  _globals['_GETLOGSRESPONSE']._serialized_end=159
  _globals['_LOGGINGSERVICE']._serialized_start=162
  _globals['_LOGGINGSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
